"""
Constants for the algorithms and the program itself.
"""

DEFAULT_MUTATION_RATE = 0.01

DEFAULT_CROSSOVER_RATE = 0.8
DEFAULT_GENERATIONS = 3000
DEFAULT_POPULATION_SIZE = 300
DEFAULT_OUTPUT_IMAGE = "result.png"

DEFAULT_NUMBER_OF_PARENTS = 3
DEFAULT_K = 3
DEFAULT_IMMIGRANT_RATE = 0.35

MAX_RANDOM_PER_ROW = 4
MIN_VALUE_PER_CELL = 1
MAX_VALUE_PER_CELL = 9
DEFAULT_BOARD_SIZE = 9
