[project]
name = "puzzle-8"
version = "0.1.0"
description = "Puzzle-8 AI"
requires-python = ">=3.12"
dependencies = [
    "alive-progress>=3.2.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pyqt5>=5.15.11",
]
